general {
    lock_cmd = pidof hyprlock || hyprlock       # Comanda pentru blocare
    before_sleep_cmd = loginctl lock-session    # Blochează înainte de suspend/sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # Aprinde ecranul după wake-up
}

# 1. Scade luminozitatea după 2.5 minute (economie baterie)
listener {
    timeout = 150                                
    on-timeout = brightnessctl set 10%          
    on-resume = brightnessctl set 100%          
}

# 2. Blochează ecranul după 10 minute
listener {
    timeout = 600                                
    on-timeout = loginctl lock-session           
}

# 3. Stinge monitorul după 10.5 minute
listener {
    timeout = 630                                
    on-timeout = hyprctl dispatch dpms off       
    on-resume = hyprctl dispatch dpms on         
}

# 4. Suspend sistemul după 15 minute
listener {
    timeout = 900                                
    on-timeout = systemctl suspend               
}
